"""HTML report generation with embedded styling."""

from __future__ import annotations

from pathlib import Path

from jinja2 import Template

from odcp.models import ScanReport

_HTML_TEMPLATE = Template("""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ODCP Report: {{ env_name }}</title>
<style>
  :root { --green: #22c55e; --yellow: #eab308; --red: #ef4444; --gray: #6b7280; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         background: #f8fafc; color: #1e293b; line-height: 1.6; padding: 2rem; }
  .container { max-width: 1100px; margin: 0 auto; }
  h1 { font-size: 1.8rem; margin-bottom: 0.5rem; }
  h2 { font-size: 1.3rem; margin: 2rem 0 1rem; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.5rem; }
  .meta { color: var(--gray); font-size: 0.9rem; margin-bottom: 2rem; }
  .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
  .card { background: #fff; border-radius: 8px; padding: 1.2rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); text-align: center; }
  .card .value { font-size: 2rem; font-weight: 700; }
  .card .label { font-size: 0.85rem; color: var(--gray); }
  .card.green .value { color: var(--green); }
  .card.yellow .value { color: var(--yellow); }
  .card.red .value { color: var(--red); }
  table { width: 100%; border-collapse: collapse; background: #fff; border-radius: 8px;
          overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin-bottom: 1.5rem; }
  th { background: #f1f5f9; text-align: left; padding: 0.75rem 1rem; font-weight: 600; font-size: 0.85rem; }
  td { padding: 0.6rem 1rem; border-top: 1px solid #e2e8f0; font-size: 0.9rem; }
  tr:nth-child(even) td { background: #f8fafc; }
  .status-runnable { color: var(--green); font-weight: 600; }
  .status-blocked { color: var(--red); font-weight: 600; }
  .status-partially_runnable { color: var(--yellow); font-weight: 600; }
  .status-unknown { color: var(--gray); }
  .finding { background: #fff; border-radius: 6px; padding: 1rem; margin-bottom: 0.75rem;
             box-shadow: 0 1px 2px rgba(0,0,0,0.05); border-left: 4px solid var(--gray); }
  .finding.sev-critical, .finding.sev-high { border-left-color: var(--red); }
  .finding.sev-medium { border-left-color: var(--yellow); }
  .finding .title { font-weight: 600; }
  .finding .desc { font-size: 0.9rem; color: #475569; margin-top: 0.25rem; }
  footer { margin-top: 3rem; text-align: center; color: var(--gray); font-size: 0.8rem; }
</style>
</head>
<body>
<div class="container">
  <h1>ODCP Scan Report</h1>
  <div class="meta">
    <strong>{{ env_name }}</strong> &middot;
    {{ scan_time }} &middot;
    {% if platform %}{{ platform }}{% endif %}
  </div>

  <div class="cards">
    <div class="card"><div class="value">{{ rs.total_detections }}</div><div class="label">Total Detections</div></div>
    <div class="card green"><div class="value">{{ rs.runnable }}</div><div class="label">Runnable</div></div>
    <div class="card yellow"><div class="value">{{ rs.partially_runnable }}</div><div class="label">Partial</div></div>
    <div class="card red"><div class="value">{{ rs.blocked }}</div><div class="label">Blocked</div></div>
    <div class="card"><div class="value">{{ "%.0f"|format(rs.overall_score * 100) }}%</div><div class="label">Readiness Score</div></div>
    <div class="card"><div class="value">{{ ds.total }}</div><div class="label">Dependencies</div></div>
  </div>

  <h2>Detection Readiness</h2>
  <table>
    <thead><tr><th>Detection</th><th>Status</th><th>Score</th><th>Missing</th></tr></thead>
    <tbody>
    {% for sc in scores[:50] %}
    <tr>
      <td>{{ sc.detection_name }}</td>
      <td class="status-{{ sc.status.value }}">{{ sc.status.value }}</td>
      <td>{{ "%.0f"|format(sc.score * 100) }}%</td>
      <td>{{ sc.missing_dependencies }}</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>

  {% if dep_by_kind %}
  <h2>Dependencies by Kind</h2>
  <table>
    <thead><tr><th>Kind</th><th>Count</th></tr></thead>
    <tbody>
    {% for kind, count in dep_by_kind %}
    <tr><td>{{ kind }}</td><td>{{ count }}</td></tr>
    {% endfor %}
    </tbody>
  </table>
  {% endif %}

  {% if findings %}
  <h2>Top Findings ({{ findings|length }} total)</h2>
  {% for f in findings[:30] %}
  <div class="finding sev-{{ f.severity.value }}">
    <div class="title">[{{ f.severity.value|upper }}] {{ f.title }}</div>
    <div class="desc">{{ f.description }}</div>
  </div>
  {% endfor %}
  {% endif %}

  <footer>Generated by ODCP &mdash; Open Detection Control Plane</footer>
</div>
</body>
</html>
""")


def generate_html_report(report: ScanReport) -> str:
    """Render a self-contained HTML report."""
    rs = report.readiness_summary
    ds = report.dependency_stats
    platform = ""
    if report.environment.platforms:
        p = report.environment.platforms[0]
        platform = f"{p.vendor} ({p.adapter_type})"

    scores = sorted(report.readiness_scores, key=lambda s: s.score)
    dep_by_kind = sorted(ds.by_kind.items(), key=lambda x: -x[1]) if ds.by_kind else []

    return _HTML_TEMPLATE.render(
        env_name=report.environment.name,
        scan_time=report.scan_timestamp.strftime("%Y-%m-%d %H:%M:%S UTC"),
        platform=platform,
        rs=rs,
        ds=ds,
        scores=scores,
        dep_by_kind=dep_by_kind,
        findings=sorted(report.findings, key=lambda f: f.severity.value),
    )


def write_html_report(report: ScanReport, path: Path) -> None:
    """Write an HTML report to a file."""
    path.write_text(generate_html_report(report), encoding="utf-8")
