"""Markdown report generation."""

from __future__ import annotations

from pathlib import Path

from odcp.models import ScanReport


def generate_markdown_report(report: ScanReport) -> str:
    """Generate a comprehensive Markdown report from scan results."""
    lines: list[str] = []
    rs = report.readiness_summary
    ds = report.dependency_stats

    # Header
    lines.append(f"# ODCP Scan Report: {report.environment.name}")
    lines.append("")
    lines.append(f"**Scan timestamp:** {report.scan_timestamp.strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"**Environment:** {report.environment.name}")
    if report.environment.platforms:
        p = report.environment.platforms[0]
        lines.append(f"**Platform:** {p.vendor} ({p.adapter_type})")
    lines.append("")

    # Executive Summary
    lines.append("## Executive Summary")
    lines.append("")
    pct = f"{rs.overall_score * 100:.1f}%"
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total detections | {rs.total_detections} |")
    lines.append(f"| Runnable | {rs.runnable} |")
    lines.append(f"| Partially runnable | {rs.partially_runnable} |")
    lines.append(f"| Blocked | {rs.blocked} |")
    lines.append(f"| Unknown | {rs.unknown} |")
    lines.append(f"| Overall readiness score | {pct} |")
    lines.append("")

    # Dependency Statistics
    lines.append("## Dependency Statistics")
    lines.append("")
    lines.append(f"**Total dependencies:** {ds.total}")
    lines.append("")
    if ds.by_kind:
        lines.append("### By Kind")
        lines.append("")
        lines.append("| Kind | Count |")
        lines.append("|------|-------|")
        for kind, count in sorted(ds.by_kind.items(), key=lambda x: -x[1]):
            lines.append(f"| {kind} | {count} |")
        lines.append("")
    if ds.by_status:
        lines.append("### By Status")
        lines.append("")
        lines.append("| Status | Count |")
        lines.append("|--------|-------|")
        for status, count in sorted(ds.by_status.items(), key=lambda x: -x[1]):
            lines.append(f"| {status} | {count} |")
        lines.append("")

    # Detection Readiness Breakdown
    lines.append("## Detection Readiness")
    lines.append("")
    if report.readiness_scores:
        lines.append("| Detection | Status | Score | Missing Deps |")
        lines.append("|-----------|--------|-------|--------------|")
        sorted_scores = sorted(report.readiness_scores, key=lambda s: s.score)
        for sc in sorted_scores[:50]:
            status_icon = _status_icon(sc.status.value)
            lines.append(
                f"| {sc.detection_name} | {status_icon} {sc.status.value} "
                f"| {sc.score:.0%} | {sc.missing_dependencies} |"
            )
        if len(report.readiness_scores) > 50:
            lines.append(f"| ... and {len(report.readiness_scores) - 50} more | | | |")
        lines.append("")

    # Top Findings
    if report.findings:
        lines.append("## Findings")
        lines.append("")
        lines.append(f"**Total findings:** {len(report.findings)}")
        lines.append("")

        # Group by severity
        by_severity: dict[str, list] = {}
        for f in report.findings:
            by_severity.setdefault(f.severity.value, []).append(f)

        for sev in ("critical", "high", "medium", "low", "info"):
            group = by_severity.get(sev, [])
            if group:
                lines.append(f"### {sev.upper()} ({len(group)})")
                lines.append("")
                for f in group[:20]:
                    lines.append(f"- **{f.title}**")
                    lines.append(f"  {f.description}")
                    if f.remediation:
                        lines.append(f"  *Remediation:* {f.remediation.description}")
                    lines.append("")
                if len(group) > 20:
                    lines.append(f"  ... and {len(group) - 20} more {sev} findings")
                    lines.append("")

    # Most common missing dependency types
    missing_by_kind: dict[str, int] = {}
    for dep in report.dependencies:
        if dep.status.value == "missing":
            missing_by_kind[dep.kind.value] = missing_by_kind.get(dep.kind.value, 0) + 1
    if missing_by_kind:
        lines.append("## Most Common Missing Dependency Types")
        lines.append("")
        lines.append("| Type | Count |")
        lines.append("|------|-------|")
        for kind, count in sorted(missing_by_kind.items(), key=lambda x: -x[1]):
            lines.append(f"| {kind} | {count} |")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [ODCP](https://github.com/yunkewang/open-detection-control-plane)*")
    lines.append("")

    return "\n".join(lines)


def write_markdown_report(report: ScanReport, path: Path) -> None:
    """Write a Markdown report to a file."""
    path.write_text(generate_markdown_report(report), encoding="utf-8")


def _status_icon(status: str) -> str:
    return {
        "runnable": "✅",
        "partially_runnable": "⚠️",
        "blocked": "❌",
        "unknown": "❓",
    }.get(status, "")
