# =============================================================================
# Example Splunk transforms for ODCP testing
# =============================================================================

[ip_reputation_lookup]
filename = ip_reputation.csv
max_matches = 1

[asset_lookup]
filename = assets.csv
max_matches = 1

[authorized_regions_lookup]
filename = authorized_regions.csv
max_matches = 1
